name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter upgrade
      - run: flutter clean
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: flutter build web --dart-define=APPNAME='${{ secrets.APPNAME }}'

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOTE_APP_1BE09 }}'
          channelId: live
          projectId: note-app-1be09